cc_library(
    name = "logger",
    srcs = ["Logger.cpp"],
    hdrs = ["Logger.hpp"],
    visibility = ["//visibility:public"],
    includes = ["."],
    deps = [
        "//app/libs/datetime:datetime",
        "@spdlog//:spdlog",
    ],
)