cc_binary(
    name="main",
    srcs = ["main.cpp"],
    deps = [
        "//app/libs/logger:logger",
        "//app/libs/ws2812:neopixel",  # Dependency on the neopixel library.
    ],
    visibility = ["//visibility:public"],
)
